# Generated by Django 5.0.3 on 2024-04-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('translator', 'translator'), ('project_manager', 'project_manager'), ('chief_editor', 'chief_editor')], max_length=50),
        ),
    ]
