# Generated by Django 5.0.3 on 2024-04-11 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='ProjectInfo',
        ),
    ]
