# Generated by Django 5.0.3 on 2024-04-11 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_project_projectinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectInfo',
        ),
    ]
