# Generated by Django 5.0.3 on 2024-04-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='selected_translator',
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(default='Not completed', editable=False, max_length=20),
        ),
    ]
