# Generated by Django 5.0.3 on 2024-04-29 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='name',
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='remaining_text_volume',
            field=models.CharField(default='0%', max_length=100),
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(default='Not Completed', max_length=100),
        ),
        migrations.AlterField(
            model_name='activity',
            name='translator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
