# Generated by Django 5.0.3 on 2024-04-29 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_delete_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=255)),
                ('translator', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
                ('remaining_text_volume', models.CharField(default='0%', max_length=100)),
                ('status', models.CharField(default='Not Completed', max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='app.project')),
            ],
        ),
    ]
